### ISSUE TITLE
This (degenerate) spec hits walk limit when it shouldn't

### ISSUE THREAD

**Issue by jsccast** [Comcast/sheens#26]
```yaml
name: degenerate
nodes:
  start:
    branching:
      branches:
      - target: done
  done:
```

If you `Walk` a machine with that spec _with_ a pending message, the walking hits its limit (instead of terminating at the terminal node `done`.
