### ISSUE TITLE
Apparent infinite loop when action doesn't return bindings

### ISSUE THREAD

**Issue by jsccast** [Comcast/sheens#44]
The spec

```YAML
name: infiniteLoop
description: |
  Send {"wants":"tacos"} to this machine, and you'll get
  an infinite loop.

  (The action doesn't return anything.)
patternsyntax: json
nodes:
  start:
    branching:
      type: message
      branches:
      - pattern: |
          {"wants":"?wanted"}
        target: deliver
  deliver:
    action:
      interpreter: ecmascript
      source: |-
        _.out({"send": _.bindings["?wanted"]})
        // Nothing returned.
    branching:
      branches:
      - target: start
```

when given `{"wants":tacos"}` via

```Shell
msimple -s specs/infiniteLoop.yaml -d
```

loops infinitely.
